image: debian/stretch
packages:
  - rsync
  - ruby
  - ruby-dev
  - zlib1g-dev
sources:
  - https://github.com/WayfireWM/wayfire.org
environment:
  deploy: deploy@wayfire.org
secrets:
  - 302ef3e2-48f3-4eba-b391-b733af854947
triggers:
  - action: email
    condition: always
    to: Ilia Bozhinov <ammen99@gmail.com>
tasks:
  - setup: |
      sudo gem install github-pages
  - build: |
      cd wayfire.org
      jekyll build
  - deploy: |
      cd wayfire.org
      sshopts="-o StrictHostKeyChecking=no"
      rsync --rsh="ssh $sshopts" -rP _site/ ${deploy}:/var/www/wayfire.org/
